=== renlm/Java/MyAll/src/test/resources/.Generator.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="qualified">
	<xsd:element name="generator" type="Generator">
		<xsd:key name="module">
			<xsd:selector xpath="module"></xsd:selector>
			<xsd:field xpath="@package"></xsd:field>
			<xsd:field xpath="@name"></xsd:field>
		</xsd:key>
	</xsd:element>

	<xsd:complexType name="Generator">
		<xsd:sequence>
			<xsd:element name="url" />
			<xsd:element name="username" />
			<xsd:element name="password" />
			<xsd:element name="module" type="Module" minOccurs="0"
				maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="ds-annotation" type="xsd:string" use="optional" />
	</xsd:complexType>

	<xsd:complexType name="Module">
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="table">
				<xsd:complexType mixed="true">
					<xsd:attribute name="schema" type="xsd:string"
						use="optional" />
					<xsd:attribute name="author" type="xsd:string"
						use="required" />
					<xsd:attribute name="name" type="xsd:string"
						use="required" />
					<xsd:attribute name="schema" type="xsd:string"
						use="optional" />
					<xsd:attribute name="primary-key" type="xsd:string"
						use="optional" />
					<xsd:attribute name="comment" type="xsd:string"
						use="optional" />
					<xsd:attribute name="entity-prefix" type="xsd:string"
						use="optional" />
					<xsd:attribute name="force" type="xsd:boolean"
						use="optional" default="false" />
				</xsd:complexType>
			</xsd:element>
		</xsd:choice>
		<xsd:attribute name="name" type="xsd:string"
			use="required" />
		<xsd:attribute name="package" type="xsd:string"
			use="required" />
	</xsd:complexType>
</xsd:schema>

=== renlm/Java/MyGenerator/src/test/resources/Generator.PostgreSQL.xml
<?xml version="1.0" encoding="UTF-8"?>
<generator dsName="pg"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation=".Generator.xsd">

	<url>jdbc:postgresql://114.67.87.80:5432/crawler</url>
	<username>crawler</username>
	<password>crawler@(ddf_^)</password>
	<driverName>org.postgresql.Driver</driverName>

	<module name="sys" package="cn.renlm.crawler">
		<table schema="public" author="任黎明" name="sys_const" />
		<table schema="public" author="任黎明" name="sys_dict" />
		<table schema="public" author="任黎明" name="sys_tree" />
		<table schema="public" author="任黎明" name="sys_file" idType="ASSIGN_ID" />
	</module>
</generator>
